service:
  name: analytics-service
  image: karandh/analytics-service:latest
  replicas: 1
  port: 3003
  type: ClusterIP

hpa:
  enabled: false

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

configData:
  SERVICE_NAME: "analytics-service"
  ENVIRONMENT: "dev"
  LOG_LEVEL: "debug"
  # Kafka consumer config
  KAFKA_BROKERS: "kafka.dd-dev.svc.cluster.local:9092"
  KAFKA_TOPIC: "content-events"
  KAFKA_GROUP_ID: "analytics-consumers"

secretData: {}

networkPolicy:
  enabled: false