service:
  name: content-service
  image: karandh/content-service:latest
  replicas: 1
  port: 3002
  type: ClusterIP

hpa:
  enabled: false

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

configData:
  SERVICE_NAME: "content-service"
  ENVIRONMENT: "dev"
  LOG_LEVEL: "debug"
  # Kafka producer config
  KAFKA_BROKERS: "kafka.dd-dev.svc.cluster.local:9092"
  KAFKA_TOPIC: "content-events"

secretData: {}

networkPolicy:
  enabled: false