{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dd-service.fullname" . }}-deny-all
  labels:
    {{- include "dd-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dd-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow all pods in the same namespace to communicate by default
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
{{- end }}
