{{- if .Values.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dd-service.fullname" . }}-secret
  labels:
    {{- include "dd-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
