service:
  name: api-gateway
  image: karandh/api-gateway:latest
  replicas: 3
  port: 3001
  type: NodePort
  nodePort: 30081

ingress:
  enabled: true
  host: api.displaydata.prod

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  cpuThreshold: 60

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

configData:
  SERVICE_NAME: "api-gateway"
  ENVIRONMENT: "prod"
  CONTENT_SERVICE_URL: "http://content-service:3002"
  AUTH_SERVICE_URL: "http://auth-service:3004"
  LOG_LEVEL: "info"

secretData:
  JWT_SECRET: "c3VwZXItc2VjcmV0LWtleS1mb3ItcHJvZA==" # super-secret-key-for-prod
  API_KEY: "cHJvZC1hcGkta2V5LXNlY3VyZQ==" # prod-api-key-secure

networkPolicy:
  enabled: true
