service:
  name: content-service
  image: karandh/content-service:latest
  replicas: 2
  port: 3002
  type: ClusterIP

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuThreshold: 70

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

configData:
  SERVICE_NAME: "content-service"
  ENVIRONMENT: "prod"
  LOG_LEVEL: "info"
  # Kafka producer config
  KAFKA_BROKERS: "kafka.dd-prod.svc.cluster.local:9092"
  KAFKA_TOPIC: "content-events"

secretData: {}

networkPolicy:
  enabled: true